### ISSUE TITLE
backend error exception

### ISSUE THREAD

**Issue by jrhoops304** [hpe-storage/truenas-csp#73]
not an expert by any means but following the install guide I am receiving this error:

Mon, 24 Mar 2025 21:01:33 +0000 backend ERROR Exception: Traceback (most recent call last):
  File "/app/truenascsp.py", line 420, in on_post
    if '0.0.0.0' in api.discovery_ips():
                    ^^^^^^^^^^^^^^^^^^^
  File "/app/backend.py", line 293, in discovery_ips
    for listen in portal.get('listen'):
                  ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

I am not using 0.0.0.0 in truenas iSCSI config but I do have a separate storage network iSCSI is being served on.

**Comment by datamattsson** [comment]
Hey! Thanks for reporting this. You can only have one portal with "hpe-csi" in the description but you can have multiple IP addresses attached to the portal. There will be some more sensible error messages in the next releases.

**Comment by MVB-jrhoops** [comment]
Ok. So the pvc fails or stays pending and this is the log output, is this an issue with the truenas api that needs updated in next release of truenas-csp? I’m running 2.5.1 of the hpe-csi

**Comment by datamattsson** [comment]
It's a configuration issue on your appliance. You can only have one portal with "hpe-csi" as the description.

**Comment by MVB-jrhoops** [comment]
I’ll look into this or read more on it as I don’t have any portals on true-bad named or described hpe-csi

**Comment by datamattsson** [comment]
> I’ll look into this or read more on it as I don’t have any portals on true-bad named or described hpe-csi

Oh, ok. Yes, you'll actually get the same error if you have no portals at all right now.

**Comment by MVB-jrhoops** [comment]
I completely misunderstood the requirement of the description, I just supplied the existing.  I got a little further along but now receive:  TrueNAS API returned: { "path": [ { "message": "null not allowed", "errno": 22 } ] })

**Comment by datamattsson** [comment]
This has been addressed in v2.5.2 and should yield better error messages.

**Comment by jrhoops304** [comment]
on 2.5.2 I still get this:

![Image](https://github.com/user-attachments/assets/d685fd96-1674-42df-bf87-b09e0e733f6d)

in audit log I see this:

![Image](https://github.com/user-attachments/assets/5fcb0bf4-05fc-4f70-b388-e77596337f9f)
I'm sure this is a config error on truenas but not sure what the csp is looking for

**Comment by MVB-jrhoops** [comment]
I am on 24.10.2, I posted in truenas forums for assistance on tracking truenas logs down as it is not readily apparent to me.  I will turn on debug logs but I'm not sure how specifically, is that an environment variable? if so what value and level?

**Comment by datamattsson** [comment]
> if so what value and level?

It's a Helm chart parameter: https://artifacthub.io/packages/helm/truenas-csp/truenas-csp#configuration-and-installation

Install the Helm chart with `--set logDebug=true`. You can modify a running TrueNAS CSP with the following in the container spec.

```
env:
- name: LOG_DEBUG
  value: "1"
```

**Comment by MVB-jrhoops** [comment]
it appears to not be creating it, in the truesnas audit logs I see success: false but I don't see any other details around that tailing middleware.log or messages:

![Image](https://github.com/user-attachments/assets/dd9a9cee-ee65-476b-8694-da30958988c8)

I'll keep digging, I believe this is a truenas failure just not certain why

**Comment by datamattsson** [comment]
> I'll keep digging, I believe this is a truenas failure just not certain why

There's no failure in the above log?

**Comment by MVB-jrhoops** [comment]
cut off the bottom of the screenshot since same as before:

![Image](https://github.com/user-attachments/assets/ed69c0a9-d3be-4080-96bd-87521f40720f)

 it states "can't find the pvc-9f6xxxxxxxxxxxxxxx" volume.  also looking in truenas I do not see the pvc volume either so truenas is not creating it, it seems. in the audit logs for this method call it does state "success" : false

**Comment by datamattsson** [comment]
I interpret this as the API is demanding the the volume creation parameter `path` to not be `null`. Which is very odd.

The only thing I can think of is that `path` is not properly inherited from `iscsi2` in your path. `iscsi2` has to be a "FILESYSTEM", not a "VOLUME".

This is my "root" filesystem:

![Image](https://github.com/user-attachments/assets/411a242b-1e0f-43c5-99d9-944644aefdfd)

**Comment by MVB-jrhoops** [comment]
this is my issue. its a block device.  I'll delete/reconfigure

**Comment by MVB-jrhoops** [comment]
that did resolve the issue.

**Comment by datamattsson** [comment]
Great! Thanks for checking out the CSP and working out this issue.

I added emphasis on "FILESYSTEM" in #77 underneath the [`StorageClass` ](https://github.com/hpe-storage/truenas-csp/blob/master/INSTALL.md#example-storageclass)if others find themselves here.

**Comment by MVB-jrhoops** [comment]
well. thank you for the support, above and beyond, excellent tool to meet this need

**Comment by datamattsson** [comment]
> excellent tool to meet this need

Spread the word and tell a friend. 😉
